<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lbo_notices"
 *
 * Auto generated by Extension Builder 2020-07-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Notices',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Pierre Boivin',
    'author_email' => 'pierre.boivin@libeo.com',
    'state' => 'stable',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
